name: Run Tests

on:
  push:
    paths:
      - .github/workflows/test.yaml
      - backend/requirements.txt
      - '**.py'
  pull_request:
    paths:
      - .github/workflows/test.yaml
      - backend/requirements.txt
      - '**.py'

jobs:
  test-pytest:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout ğŸ›ï¸
        uses: actions/checkout@v2.3.1

      - name: Setup Python 3.7 ğŸ
        uses: "actions/setup-python@v3"
        with:
          python-version: "3.7"

      - name: Install and Test ğŸ§ª
        env:
          SECRET_KEY: ${{ github.sha }}
        run: |
          ./run.sh install-backend
          ./run.sh manage migrate
          ./run.sh manage test
